// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsfmkscdadlieqedfuth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZm1rc2NkYWRsaWVxZWRmdXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDMxNTIsImV4cCI6MjA2MDg3OTE1Mn0.1hjCS_1CepR78WNo2W0TcA3AUGldg274ApUxabDA_EM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);